### ISSUE TITLE
No license information found in this repository

### ISSUE THREAD

**Issue by dancesWithCycles** [geshan/nodejs-posgresql#29]
Hi @geshan  ,
Thank you so much for providing this repository and the related block post. It is so helpful. Bit appreciation!

I have not found any license information in this repository. Do I not see the wood for the trees? ;-)

Do you mind adding a license? Personally, I tend to say open source can not be ranked highest. If you ask me, I suggest licenses like GNU GPL. [This](https://www.gnu.org/licenses/license-list.html#DocumentationLicenses) is a good list of open source licenses with comparison.

Cheers!

**Comment by geshan** [comment]
@dancesWithCycles added MIT license, thanks!

**Comment by geshan** [comment]
@dancesWithCycles what do you plan to do with the code? :)

**Comment by dancesWithCycles** [comment]
> @dancesWithCycles added MIT license, thanks!

Hi @geshan ,
Good morning from Brunswick, Germany! You are welcome! Cheers!

**Comment by dancesWithCycles** [comment]
> @dancesWithCycles what do you plan to do with the code? :)

Hi @geshan ,
I am using it as an example for a REST API for psql. That was the intention, wasn't it?

Cheers!

**Comment by geshan** [comment]
> > @dancesWithCycles what do you plan to do with the code? :)
> 
> Hi @geshan , I am using it as an example for a REST API for psql. That was the intention, wasn't it?
> 
> Cheers!

Go ahead and use it.
